"""empty message

Revision ID: 560eca2f4781
Revises: b5f9aff88d41
Create Date: 2025-06-28 10:40:05.205095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560eca2f4781'
down_revision = 'b5f9aff88d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_image_url_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_unique_constraint('posts_image_url_key', ['image_url'])

    # ### end Alembic commands ###
